### ISSUE TITLE
Terraform init failed

### ISSUE THREAD

**Issue by praveenambati1233** [Azure-Samples/github-terraform-oidc-ci-cd#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Follow the latest README.md to rename the virtual machine.

### Any log messages given by the failure
> job url - https://github.com/praveenambati1233/ambati-20241118-cute-pheasant/actions/runs/11881380831/job/33105646870?pr=1

/home/runner/work/_temp/39b9043b-d84f-4097-aebf-085cade13340/terraform-bin init -backend-config=resource_group_name=*** -backend-config=storage_account_name=*** -backend-config=container_name=***
Initializing the backend...
╷
│ Error: Failed to get existing workspaces: Error retrieving keys for Storage Account "***": storage.AccountsClient#ListKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'f4785a58-9d9c-45ad-9ba7-780ab0a92c4c' with object id 'f4785a58-9d9c-45ad-9ba7-780ab0a92c4c' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/listKeys/action' over scope '/subscriptions/***/resourceGroups/***/providers/Microsoft.Storage/storageAccounts/***' or the scope is invalid. If access was recently granted, please refresh your credentials."
│ 
│ 
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.

### Expected/desired behavior
> Able to rename the Virtual Machine name and terraform lifecyle should work fine.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?) github hosted runners

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jaredfholgate** [comment]
Added this line to fix it: https://github.com/Azure-Samples/github-terraform-oidc-ci-cd/blob/6afb1a86a8693f697b96c27718a212ffd28c1dc9/.github/workflows/main.yml#L29

**Comment by praveenambati1233** [comment]
Thank You for your response. That didn't fix the problem - https://github.com/praveenambati1233/ambati-20241118-cute-pheasant/actions/runs/11935377685/job/33266562445?pr=1

I think the issue is the Storage Account role ?

**Comment by jaredfholgate** [comment]
If that was the case, this run would have failed: https://github.com/praveenambati1233/ambati-20241118-cute-pheasant/actions/runs/11881226967

**Comment by jaredfholgate** [comment]
You need to add that env var here: https://github.com/praveenambati1233/ambati-20241118-cute-pheasant/blob/069b762c2e29bcd0d1febe4ce46927d3ea067066/.github/workflows/main.yml#L28

**Comment by jaredfholgate** [comment]
You need to remove the extra underscore from here: https://github.com/praveenambati1233/ambati-20241118-cute-pheasant/blob/2031e41ede4ba895136f8fced0262393a50d35f6/.github/workflows/main.yml#L29
